### ISSUE TITLE
[DepRCNN] L141

### ISSUE THREAD

**Issue by zeeeyang** [zhouh/dynamic-reranker#1]
Is this line [DepRCNN L141](https://github.com/zhouh/dynamic-reranker/blob/bc76e88a78e3516f9b9b133e6c6db021f8ba19ca/bestFirstDepRerank/DepRCNN.java#L141) correct?

**Comment by zhouh** [comment]
Hi,

Thanks for your email.
This is a bug, which affects the children distance features of the rcnn.
But I don't know whether this feature have a remarkable influence to the
rcnn performance or not.
Maybe the model could be further enhanced a bit.

Regards,
Hao

**Comment by zeeeyang** [comment]
Hi Hao, 

Thank you. I also think it doesn't matter a lot. 

Best,
Zhiyang
